# Copyright 2024 Xin Huang
#
# GNU General Public License v3.0
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, please see
#
#    https://www.gnu.org/licenses/gpl-3.0.en.html


import numpy as np
from itertools import product


def filter_combinator(combinator, blacklist):
    def filtered_combinator(*args, **kwargs):
        for wc_comb in combinator(*args, **kwargs):
            # Use frozenset instead of tuple
            # in order to accomodate
            # unpredictable wildcard order
            if frozenset(wc_comb) not in blacklist:
                yield wc_comb
    return filtered_combinator

forbidden = {
    frozenset({"i": i, "w": w, "x": x, "y": 0, "z": 0}.items())
    for i, w, x in product(range(1, 23), [0.01, 0.05, 0.1], [0.5, 0.8])
}

filtered_product = filter_combinator(product, forbidden)


##### Target rules #####


rule all:
    input:
        expand(
            "results/sai/1src/{dataset}/{src}/w_{w}_x_{x}_y_{y}/{dataset}.{src}.w_{w}_x_{x}_y_{y}_{stat}_outliers.tsv",
            i=list(range(1,23)),
            w=[0.01, 0.05, 0.1],
            x=[0.5, 0.8],
            y=[1],
            src=['nea', 'den'],
            stat=['U', 'Q95'],
            dataset=['1KG', 'lit'],
        ),
        expand(
            "results/sai/2src/{dataset}/nea_den/w_{w}_x_{x}_y_{y}_z_{z}/{dataset}.nea_den.w_{w}_x_{x}_y_{y}_z_{z}_{stat}_outliers.tsv",
            filtered_product,
            w=[0.01, 0.05, 0.1],
            x=[0.5, 0.8],
            y=[1, 0],
            z=[0, 1],
            stat=['U', 'Q95'],
            dataset=['1KG', 'lit'],
        ),


##### Modules #####


include: "rules/download.smk"
include: "rules/preprocess_1KG.smk"
include: "rules/preprocess_lit.smk"
include: "rules/run_sai_1src.smk"
include: "rules/run_sai_2src.smk"
