# Copyright 2024 Xin Huang
#
# GNU General Public License v3.0
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, please see
#
#    https://www.gnu.org/licenses/gpl-3.0.en.html


import numpy as np


##### Target rules #####


rule all:
    input:
        expand("results/processed_data/1KG/merged_1KG_nea.chr{i}.vcf.gz", i=np.arange(22)+1)
        #"results/sai/Lithuanians/lit.scores.txt",
        #"results/sai/Lithuanians/lit_U_outliers.tsv",
        #"results/sai/Lithuanians/lit_Q95_outliers.tsv",


##### Modules #####


include: "rules/download.smk"
include: "rules/preprocess_1KG.smk"
#include: "rules/preprocess.smk"
#include: "rules/run_sai.smk"
